# Terminal

## Stow
brew 'stow'

## Git
brew 'git'
brew 'gh'
brew 'lazygit'

## IDE
brew 'neovim'
brew 'tmux'
brew 'tmuxinator'

## CLI
brew 'zsh'
brew 'zplug'
brew 'starship'
brew 'bat'
brew 'bat-extras'
brew 'ripgrep'
brew 'zoxide'
brew 'lsd'
brew 'fd'
brew 'asciinema'

## Node.js
brew 'node'
brew 'deno'
brew 'pnpm'

## Tools
brew 'docker'
brew 'lazydocker'
brew 'postgresql'
brew 'lynx'


# Apps

## 1Password
cask '1password'
cask '1password-cli'

## Development
cask 'ghostty'
cask 'visual-studio-code'

## Utilities
cask 'jordanbaird-ice'
cask 'karabiner-elements'
cask 'raycast'
cask 'rectangle'
cask 'rocket-typist'
cask 'screen-studio'

## Communication
cask 'whatsapp'
cask 'zoom'

## Browsers
cask 'arc'
cask 'firefox'
cask 'google-chrome'

# Media
cask 'spotify'
